'use strict';

/**
 * Provider Pact Verification
 *
 * Runs AFTER the consumer has generated the pact file at ../../pacts/.
 * This test:
 *   1. Starts the real Express API on an ephemeral port
 *   2. Replays every interaction from the pact file against it
 *   3. Fails if the real API doesn't honour the consumer's expectations
 */

const { Verifier } = require('@pact-foundation/pact');
const path = require('path');
const app = require('../app');

const PROVIDER_PORT = 3002;
const PACTS_DIR = path.resolve(__dirname, '../../../pacts');

describe('Provider Pact Verification', () => {
  let server;

  beforeAll((done) => {
    server = app.listen(PROVIDER_PORT, done);
  });

  afterAll((done) => {
    server.close(done);
  });

  it('satisfies all UserConsumer contract expectations', async () => {
    const verifier = new Verifier({
      provider: 'UserProvider',
      providerBaseUrl: `http://localhost:${PROVIDER_PORT}`,

      // Read the pact file generated by the consumer tests
      pactUrls: [path.join(PACTS_DIR, 'UserConsumer-UserProvider.json')],

      // Provider state handlers — called before each interaction that declares a state.
      // Our in-memory store always has the right data, so most are no-ops here.
      // In a real app you'd seed a test DB or stub services.
      stateHandlers: {
        'users exist': async () => {
          app.reset();
        },
        'user with id 1 exists': async () => {
          app.reset(); // Alice is id:1 in the default dataset
        },
        'user with id 999 does not exist': async () => {
          app.reset(); // 999 doesn't exist in the default dataset
        },
        'the users collection is available': async () => {
          app.reset();
        },
      },

      logLevel: 'warn',
    });

    return verifier.verifyProvider();
  }, 30_000);
});
