'use strict';

/**
 * Provider Pact Verification
 *
 * Two modes:
 *   - Broker mode (PACT_BROKER_BASE_URL set): fetches pacts from the Pact Broker
 *     and publishes the verification result back, tagged with GIT_COMMIT / GIT_BRANCH.
 *   - Local mode (no broker): reads the pact file generated by the consumer tests.
 */

const { Verifier } = require('@pact-foundation/pact');
const path = require('path');
const app = require('../app');

const PROVIDER_PORT = 3002;
const PACTS_DIR = path.resolve(__dirname, '../../../pacts');
const BROKER_URL = process.env.PACT_BROKER_BASE_URL;

function pactSource() {
  if (BROKER_URL) {
    if (!process.env.GIT_COMMIT || !process.env.GIT_BRANCH) {
      throw new Error('Broker mode needs GIT_COMMIT and GIT_BRANCH set');
    }
    return {
      pactBrokerUrl: BROKER_URL,
      consumerVersionSelectors: [
        { branch: process.env.GIT_BRANCH },
        { deployedOrReleased: true },
      ],
      publishVerificationResult: true,
      providerVersion: process.env.GIT_COMMIT,
      providerVersionBranch: process.env.GIT_BRANCH,
    };
  }
  return {
    pactUrls: [path.join(PACTS_DIR, 'UserConsumer-UserProvider.json')],
  };
}

describe('Provider Pact Verification', () => {
  let server;

  beforeAll((done) => {
    server = app.listen(PROVIDER_PORT, done);
  });

  afterAll((done) => {
    server.close(done);
  });

  it('satisfies all UserConsumer contract expectations', async () => {
    const verifier = new Verifier({
      provider: 'UserProvider',
      providerBaseUrl: `http://localhost:${PROVIDER_PORT}`,
      ...pactSource(),

      // Provider state handlers — called before each interaction that declares a state.
      stateHandlers: {
        'users exist': async () => {
          app.reset();
        },
        'user with id 1 exists': async () => {
          app.reset(); // Alice is id:1 in the default dataset
        },
        'user with id 999 does not exist': async () => {
          app.reset(); // 999 doesn't exist in the default dataset
        },
        'the users collection is available': async () => {
          app.reset();
        },
      },

      logLevel: 'warn',
    });

    return verifier.verifyProvider();
  }, 30_000);
});
